### ISSUE TITLE
build: my build fails if I add `TCACoordinators`  as a dependency

### ISSUE THREAD

**Issue by vladimirleonidovich** [johnpatrickmorgan/TCACoordinators#87]
I use XcodeGen to produce Xcode projects:
```yaml
packages:
  TCACoordinators:
    github: johnpatrickmorgan/TCACoordinators
    from: 0.12.1
```
My target's dependencies:
```yaml
    dependencies:
      - package: TCACoordinators
```
Unfortunately, these lines makes my build failing for unknown reasons. (I can successfully add other dependencies)
What am I missing? Is the package broken? It would be great if the repository had documentation on how to add this package as a dependency.
Thank you!
